### PR TITLE
Added Keyboard blocks

### PR DESCRIPTION
**Pull request by Samyocord**
It blocks Alt+Esc, Ctrl+Esc, Left and Right Windows key and Alt+F4 now.

### CODE REVIEW

**Comment by FlyTechVideos** [comment]
Todo: Investigate if this gets the exe detected by antimalware (virustotal)

**Comment by dR1pT** [comment]
Is that even functional? I can see "doesn't work" comment

**Comment by jeuxjeux20** [comment]
Added the same modifications to #14 with no conflicts.

**Comment by FlyTechVideos** [comment]
Replaced with #14

**Pull request closed without merging**
