### PR TITLE
3.1 with Slovenian language

### PR DESCRIPTION
**Pull request by mytja**
This is a translation for 3.1.
Slovenian language!

### CODE REVIEW

**Comment by iiRoco** [comment]
[Automatic translation](https://github.com/FlyTechVideos/BluescreenSimulator/tree/automatic-translation) is being implemented so I'm not sure if this is needed anymore.

**Comment by mytja** [comment]
But it is better to take a translation of a human, than a machine translation ;-)

**Comment by iiRoco** [comment]
That is true, but it only applies to the default BSoD.

**Comment by mytja** [comment]
If you think so, you can close this pull request without merging.

**Comment by mytja** [comment]
Closed this

**Pull request closed without merging**
