### PR TITLE
How To Use

### PR DESCRIPTION
**Pull request by ayjemabo**
How to use for people who do not know how to use the program

### CODE REVIEW

**Comment by CyberVictoryMan** [comment]
just read the README file properly

**Comment by ayjemabo** [comment]
nothing about it

**Comment by ayjemabo** [comment]
Anyone?

**Comment by Kenshelent** [comment]
https://www.youtube.com/watch?v=kyJPwpy6tVo&list=PLm_X5sFg1jutAEL1vGAymQ76pvzk_eIjE&index=1

**Pull request closed without merging**
